# Generated by Django 5.1.4 on 2025-01-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.TextField(max_length=100)),
                ('case_manufacturer', models.TextField(max_length=100)),
                ('case_form_factor', models.CharField(max_length=20)),
                ('case_power_supply_form_factor', models.CharField(max_length=10)),
                ('case_fan', models.IntegerField()),
                ('case_price', models.IntegerField()),
                ('case_description', models.TextField(blank=True, max_length=1500)),
                ('case_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cooling_system_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooling_system_name', models.TextField(max_length=100)),
                ('cooling_system_manufacturer', models.TextField(max_length=100)),
                ('cooling_system_socket', models.TextField(max_length=10)),
                ('cooling_system_tdp', models.IntegerField()),
                ('cooling_system_price', models.IntegerField()),
                ('cooling_system_description', models.TextField(blank=True, max_length=1500)),
                ('cooling_system_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.TextField(max_length=100)),
                ('cpu_manufacturer', models.TextField(max_length=100)),
                ('cpu_socket', models.TextField(max_length=10)),
                ('cpu_cores', models.IntegerField()),
                ('cpu_threads', models.IntegerField()),
                ('cpu_clock_speed', models.TextField(max_length=10)),
                ('cpu_tdp', models.IntegerField()),
                ('cpu_price', models.IntegerField()),
                ('cpu_description', models.TextField(blank=True, max_length=1500)),
                ('cpu_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gpu_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_name', models.TextField(max_length=100)),
                ('gpu_manufacturer', models.TextField(max_length=100)),
                ('gpu_clock_speed', models.TextField(max_length=10)),
                ('gpu_ram', models.TextField(max_length=10)),
                ('gpu_ram_type', models.TextField(max_length=10)),
                ('gpu_price', models.IntegerField()),
                ('gpu_description', models.TextField(blank=True, max_length=1500)),
                ('gpu_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_name', models.TextField(max_length=100)),
                ('motherboard_manufacturer', models.TextField(max_length=100)),
                ('motherboard_socket', models.TextField(max_length=10)),
                ('motherboard_chipset', models.TextField(max_length=10)),
                ('motherboard_ram_type', models.TextField(max_length=10)),
                ('motherboard_ram_slot', models.IntegerField()),
                ('motherboard_pci_slot', models.IntegerField()),
                ('motherboard_sata_slot', models.IntegerField()),
                ('motherboard_m2_slot', models.IntegerField()),
                ('motherboard_form_factor', models.CharField(max_length=10)),
                ('motherboard_price', models.IntegerField()),
                ('motherboard_description', models.TextField(blank=True, max_length=1500)),
                ('motherboard_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Power_supply_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_supply_name', models.TextField(max_length=100)),
                ('power_supply_manufacturer', models.TextField(max_length=100)),
                ('power_supply_power', models.IntegerField()),
                ('power_supply_form_factor', models.CharField(max_length=10)),
                ('power_supply_price', models.IntegerField()),
                ('power_supply_description', models.TextField(blank=True, max_length=1500)),
                ('power_supply_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ram_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_name', models.TextField(max_length=100)),
                ('ram_manufacturer', models.TextField(max_length=100)),
                ('ram_type', models.TextField(max_length=10)),
                ('ram_clock_speed', models.TextField(max_length=10)),
                ('ram_size', models.TextField(max_length=10)),
                ('ram_amount', models.IntegerField()),
                ('ram_price', models.IntegerField()),
                ('ram_description', models.TextField(blank=True, max_length=1500)),
                ('ram_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Storage_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.TextField(max_length=100)),
                ('storage_manufacturer', models.TextField(max_length=100)),
                ('storage_type', models.TextField(max_length=10)),
                ('storage_capacity', models.TextField(max_length=10)),
                ('storage_speed', models.TextField(max_length=10)),
                ('storage_connection', models.TextField(max_length=10)),
                ('storage_price', models.IntegerField()),
                ('storage_description', models.TextField(blank=True, max_length=1500)),
                ('storage_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Computer_build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.case_model')),
                ('cooling_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.cooling_system_model')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.cpu_model')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.gpu_model')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.motherboard_model')),
                ('power', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.power_supply_model')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ram_model')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.storage_model')),
            ],
        ),
    ]
