# Generated by Django 5.1.4 on 2025-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_name', models.TextField(max_length=100)),
                ('cpu_manufacturer', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motherboard_name', models.TextField(max_length=100)),
                ('motherboard_manufacturer', models.CharField(max_length=100)),
                ('motherboard_socket', models.TextField(max_length=10)),
                ('motherboard_chipset', models.TextField(max_length=10)),
                ('motherboard_ram_type', models.TextField(max_length=10)),
                ('motherboard_ram_slot', models.IntegerField()),
                ('motherboard_pci_slot', models.IntegerField()),
                ('motherboard_sata_slot', models.IntegerField()),
                ('motherboard_m2_slot', models.IntegerField()),
                ('motherboard_form_factor', models.CharField(max_length=10)),
                ('motherboard_description', models.TextField(blank=True, max_length=500)),
                ('motherboard_image', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
