# Generated by Django 5.1.4 on 2025-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_cooling_system_model_cooling_system_socket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooling_system_model',
            name='cooling_system_socket',
            field=models.TextField(max_length=200),
        ),
    ]
