# Generated by Django 5.1.4 on 2025-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_case_model_case_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu_model',
            name='gpu_bits',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu_model',
            name='gpu_power_consumption',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
