# Generated by Django 5.1.4 on 2025-03-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_computer_build_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer_build',
            old_name='power',
            new_name='power_supply',
        ),
    ]
