# Generated by Django 5.1.4 on 2025-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_rename_power_computer_build_power_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer_build',
            name='name',
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
