# Generated by Django 5.1.4 on 2025-04-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_rename_name_computer_build_build_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_model',
            name='case_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computer_build',
            name='build_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cooling_system_model',
            name='cooling_system_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpu_model',
            name='cpu_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gpu_model',
            name='gpu_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motherboard_model',
            name='motherboard_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='power_supply_model',
            name='power_supply_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ram_model',
            name='ram_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage_model',
            name='storage_featured',
            field=models.BooleanField(default=False),
        ),
    ]
