# Generated by Django 5.1.4 on 2025-04-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_case_model_case_featured_computer_build_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu_model',
            name='cpu_model',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gpu_model',
            name='gpu_chip',
            field=models.TextField(default=3050, max_length=100),
            preserve_default=False,
        ),
    ]
