# Generated by Django 5.1.4 on 2025-04-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_cpu_model_cpu_model_gpu_model_gpu_chip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu_model',
            old_name='cpu_model',
            new_name='cpu_type',
        ),
    ]
