# Generated by Django 5.1.4 on 2025-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_rename_cpu_model_cpu_model_cpu_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooling_system_model',
            name='cooling_system_type',
            field=models.TextField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
