# Generated by Django 5.1.4 on 2025-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_cooling_system_model_cooling_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooling_system_model',
            name='cooling_system_type',
            field=models.CharField(max_length=10),
        ),
    ]
